<?php

namespace Siwapp\CustomerBundle\Repository;

use Knp\Component\Pager\PaginatorInterface;
use Siwapp\CustomerBundle\Entity\Customer;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLike($term)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from(Customer::class, 'c')
            ->where('c.name LIKE :name')
            ->orWhere('c.identification LIKE :name')
            ->setParameter('name', '%'. $term .'%')
            ->getQuery()
            ->getResult();
    }

    public function paginatedSearch(array $params, $limit = 50, $page = 1)
    {
        if (!$this->paginator) {
            throw new \RuntimeException('You have to set a paginator first using setPaginator() method');
        }

        $qb = $this->getEntityManager()
            ->createQueryBuilder()
            ->select('c')
            ->from(Customer::class, 'c');
        foreach ($params as $field => $value) {
            if ($value === null) {
                continue;
            }
            if ($field == 'terms') {
                $terms = $qb->expr()->literal("%$value%");
                $qb->andWhere($qb->expr()->orX(
                    $qb->expr()->like('c.name', $terms),
                    $qb->expr()->like('c.identification', $terms),
                    $qb->expr()->like('c.contactPerson', $terms)
                ));
            }
        }

        $qb->leftJoin('c.invoices', 'i');
        $qb->addSelect('SUM(CASE WHEN i.gross_amount IS NULL THEN 0 ELSE i.gross_amount END) AS gross_amount');
        $qb->addSelect('SUM(CASE WHEN i.gross_amount IS NULL THEN 0 ELSE i.gross_amount END - CASE WHEN i.paid_amount IS NULL THEN 0 ELSE i.paid_amount END) AS due_amount');
        $qb->groupBy('c.id');

        return $this->paginator->paginate($qb->getQuery(), $page, $limit);
    }

    /**
     * There is no easy way to inject things into repositories yet.
     */
    public function setPaginator(PaginatorInterface $paginator)
    {
        $this->paginator = $paginator;
    }
}
