<?php

namespace Siwapp\CoreBundle\Repository;

use Siwapp\CoreBundle\Entity\Item;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLikeDescription(string $term): array
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('i')
            ->from(Item::class, 'i')
            ->orWhere('i.description LIKE :term')
            ->setParameter('term', '%'. $term .'%')
            ->getQuery()
            ->getResult();
    }
}
